export type ComponentCategory =
    | "frontend"
    | "backend"
    | "data"
    | "auth"
    | "storage"
    | "ai"
    | "infra"
    | "deployment"
    | "observability";

export const CATEGORY_ORDER: ComponentCategory[] = [
    "frontend",
    "backend",
    "data",
    "auth",
    "storage",
    "ai",
    "infra",
    "deployment",
    "observability",
];

export interface ComponentDef {
    type: string;
    category: ComponentCategory;
    subcategory?: string;
    label: string;
    provider: string;
    icon: string;
    description: string;
    tags: string[];
    complexityHint: number;
    costHint: string;
    capabilities: string[];
    defaultConfig: Record<string, unknown>;
    baseWeights: {
        buildSpeed: number;
        complexity: number;
        scalability: number;
        opsBurden: number;
        cost: number;
        lockIn: number;
        reliability: number;
        aiReadiness: number;
    };
}

type BaseWeights = ComponentDef["baseWeights"];

const BW: Record<string, BaseWeights> = {
    frontendModern: { buildSpeed: 3, complexity: -1, scalability: 2, opsBurden: -2, cost: -1, lockIn: 1, reliability: 2, aiReadiness: 1 },
    frontendSimple: { buildSpeed: 3, complexity: -2, scalability: 1, opsBurden: -2, cost: -2, lockIn: 0, reliability: 1, aiReadiness: 0 },
    frontendComplex: { buildSpeed: -1, complexity: 2, scalability: 2, opsBurden: 1, cost: 0, lockIn: 1, reliability: 1, aiReadiness: 0 },
    backendManaged: { buildSpeed: 3, complexity: -2, scalability: 2, opsBurden: -3, cost: -1, lockIn: 2, reliability: 2, aiReadiness: 1 },
    backendApi: { buildSpeed: 1, complexity: 1, scalability: 2, opsBurden: 0, cost: 0, lockIn: 0, reliability: 2, aiReadiness: 0 },
    backendComplex: { buildSpeed: -1, complexity: 2, scalability: 2, opsBurden: 1, cost: 1, lockIn: 0, reliability: 2, aiReadiness: 0 },
    dataRelational: { buildSpeed: 0, complexity: 1, scalability: 2, opsBurden: 1, cost: 1, lockIn: 0, reliability: 3, aiReadiness: 0 },
    dataManaged: { buildSpeed: 1, complexity: 0, scalability: 2, opsBurden: 0, cost: 0, lockIn: 1, reliability: 2, aiReadiness: 0 },
    cache: { buildSpeed: 1, complexity: 0, scalability: 2, opsBurden: 0, cost: 0, lockIn: 1, reliability: 1, aiReadiness: 0 },
    authManaged: { buildSpeed: 3, complexity: -2, scalability: 1, opsBurden: -2, cost: 0, lockIn: 2, reliability: 2, aiReadiness: 0 },
    authEnterprise: { buildSpeed: 1, complexity: 1, scalability: 2, opsBurden: 0, cost: 1, lockIn: 2, reliability: 2, aiReadiness: 0 },
    storageManaged: { buildSpeed: 2, complexity: -1, scalability: 2, opsBurden: -1, cost: 0, lockIn: 1, reliability: 2, aiReadiness: 0 },
    aiCore: { buildSpeed: 1, complexity: 1, scalability: 0, opsBurden: 0, cost: 2, lockIn: 1, reliability: -1, aiReadiness: 3 },
    aiSupport: { buildSpeed: 0, complexity: 1, scalability: 1, opsBurden: 0, cost: 1, lockIn: 0, reliability: 1, aiReadiness: 2 },
    infraManaged: { buildSpeed: 1, complexity: 0, scalability: 2, opsBurden: 0, cost: 0, lockIn: 1, reliability: 2, aiReadiness: 0 },
    infraComplex: { buildSpeed: -1, complexity: 2, scalability: 3, opsBurden: 1, cost: 1, lockIn: 0, reliability: 2, aiReadiness: 0 },
    deployManaged: { buildSpeed: 2, complexity: -1, scalability: 2, opsBurden: -2, cost: 0, lockIn: 2, reliability: 2, aiReadiness: 0 },
    deploySelfManaged: { buildSpeed: 0, complexity: 2, scalability: 3, opsBurden: 2, cost: 1, lockIn: 0, reliability: 3, aiReadiness: 0 },
    observabilityCore: { buildSpeed: 0, complexity: 0, scalability: 1, opsBurden: 0, cost: 1, lockIn: 0, reliability: 2, aiReadiness: 0 },
    observabilityAdvanced: { buildSpeed: -1, complexity: 1, scalability: 1, opsBurden: 1, cost: 1, lockIn: 0, reliability: 3, aiReadiness: 0 },
};

export const CATEGORY_COLORS: Record<ComponentCategory, string> = {
    frontend: "#3b82f6",
    backend: "#22c55e",
    data: "#a855f7",
    auth: "#f59e0b",
    storage: "#06b6d4",
    ai: "#ec4899",
    infra: "#64748b",
    deployment: "#10b981",
    observability: "#f97316",
};

export const CATEGORY_LABELS: Record<ComponentCategory, string> = {
    frontend: "Frontend",
    backend: "Backend",
    data: "Data",
    auth: "Auth",
    storage: "Storage",
    ai: "AI / ML",
    infra: "Infrastructure",
    deployment: "Deployment",
    observability: "Observability",
};

export const COMPONENT_CATALOG: ComponentDef[] = [
    // Frontend
    {
        type: "nextjs_app",
        category: "frontend",
        subcategory: "Web Frameworks",
        label: "Next.js Web App",
        provider: "vercel",
        icon: "Globe",
        description: "React framework with routing, server rendering, server actions, and API routes",
        tags: ["react", "ssr", "fullstack"],
        complexityHint: 2,
        costHint: "Free-Low",
        capabilities: ["ssr", "rsc", "api_routes", "middleware"],
        defaultConfig: { framework: "next.js", runtime: "node" },
        baseWeights: BW.frontendModern,
    },
    {
        type: "react_spa",
        category: "frontend",
        subcategory: "Web Frameworks",
        label: "React SPA",
        provider: "vite",
        icon: "Monitor",
        description: "Client-side React app for fast iteration and simple deployments",
        tags: ["react", "spa", "csr"],
        complexityHint: 1,
        costHint: "Free",
        capabilities: ["spa", "client_rendering"],
        defaultConfig: { framework: "react", bundler: "vite" },
        baseWeights: BW.frontendSimple,
    },
    {
        type: "vue_nuxt",
        category: "frontend",
        subcategory: "Web Frameworks",
        label: "Nuxt (Vue)",
        provider: "nuxt",
        icon: "Globe",
        description: "Vue-based full-stack framework with server rendering and static generation",
        tags: ["vue", "ssr", "fullstack"],
        complexityHint: 2,
        costHint: "Free-Low",
        capabilities: ["ssr", "static_site", "api_routes"],
        defaultConfig: { framework: "nuxt" },
        baseWeights: BW.frontendModern,
    },
    {
        type: "sveltekit_app",
        category: "frontend",
        subcategory: "Web Frameworks",
        label: "SvelteKit",
        provider: "svelte",
        icon: "Globe",
        description: "Svelte application framework with SSR and endpoint support",
        tags: ["svelte", "ssr", "fullstack"],
        complexityHint: 2,
        costHint: "Free-Low",
        capabilities: ["ssr", "api_endpoints", "static_site"],
        defaultConfig: { framework: "sveltekit" },
        baseWeights: BW.frontendModern,
    },
    {
        type: "remix_app",
        category: "frontend",
        subcategory: "Web Frameworks",
        label: "Remix",
        provider: "shopify",
        icon: "Globe",
        description: "React web framework optimized for nested routing and server data loading",
        tags: ["react", "ssr", "routing"],
        complexityHint: 2,
        costHint: "Free-Low",
        capabilities: ["ssr", "data_loading", "nested_routes"],
        defaultConfig: { framework: "remix" },
        baseWeights: BW.frontendModern,
    },
    {
        type: "astro_app",
        category: "frontend",
        subcategory: "Web Frameworks",
        label: "Astro",
        provider: "astro",
        icon: "Globe",
        description: "Content-focused framework for static and hybrid websites",
        tags: ["astro", "static", "islands"],
        complexityHint: 1,
        costHint: "Free-Low",
        capabilities: ["static_site", "islands_architecture", "content_sites"],
        defaultConfig: { framework: "astro" },
        baseWeights: BW.frontendSimple,
    },
    {
        type: "mobile_app",
        category: "frontend",
        subcategory: "Mobile",
        label: "React Native App",
        provider: "react-native",
        icon: "Smartphone",
        description: "Cross-platform mobile app using React Native",
        tags: ["mobile", "cross_platform"],
        complexityHint: 4,
        costHint: "Medium",
        capabilities: ["mobile_ui", "push_notifications", "native_apis"],
        defaultConfig: { framework: "react-native" },
        baseWeights: BW.frontendComplex,
    },
    {
        type: "flutter_app",
        category: "frontend",
        subcategory: "Mobile",
        label: "Flutter App",
        provider: "google",
        icon: "Smartphone",
        description: "Cross-platform mobile app using Flutter",
        tags: ["mobile", "cross_platform", "dart"],
        complexityHint: 4,
        costHint: "Medium",
        capabilities: ["mobile_ui", "offline_sync", "native_apis"],
        defaultConfig: { framework: "flutter" },
        baseWeights: BW.frontendComplex,
    },
    {
        type: "electron_desktop",
        category: "frontend",
        subcategory: "Desktop",
        label: "Electron / Tauri Desktop",
        provider: "electron/tauri",
        icon: "Monitor",
        description: "Desktop app packaging for web technologies",
        tags: ["desktop", "cross_platform"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["desktop_app", "native_shell", "auto_updates"],
        defaultConfig: { framework: "electron" },
        baseWeights: BW.frontendComplex,
    },

    // Backend
    {
        type: "convex_backend",
        category: "backend",
        subcategory: "Managed Backends",
        label: "Convex Backend",
        provider: "convex",
        icon: "Server",
        description: "Serverless backend with reactive database queries and functions",
        tags: ["serverless", "managed", "realtime"],
        complexityHint: 1,
        costHint: "Free-Low",
        capabilities: ["realtime", "mutations", "actions", "scheduler"],
        defaultConfig: { platform: "convex" },
        baseWeights: BW.backendManaged,
    },
    {
        type: "node_express_api",
        category: "backend",
        subcategory: "API Services",
        label: "Node.js + Express API",
        provider: "nodejs",
        icon: "Server",
        description: "Lightweight Node API server",
        tags: ["node", "rest", "public_api"],
        complexityHint: 2,
        costHint: "Low",
        capabilities: ["rest_api", "middleware", "webhooks"],
        defaultConfig: { framework: "express" },
        baseWeights: BW.backendApi,
    },
    {
        type: "nestjs_api",
        category: "backend",
        subcategory: "API Services",
        label: "NestJS API",
        provider: "nestjs",
        icon: "Server",
        description: "Structured Node framework for enterprise APIs",
        tags: ["node", "typescript", "public_api"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["rest_api", "graphql", "dependency_injection"],
        defaultConfig: { framework: "nestjs" },
        baseWeights: BW.backendApi,
    },
    {
        type: "fastapi_backend",
        category: "backend",
        subcategory: "API Services",
        label: "FastAPI Backend",
        provider: "python",
        icon: "Server",
        description: "High-performance Python API framework",
        tags: ["python", "rest", "public_api"],
        complexityHint: 2,
        costHint: "Low",
        capabilities: ["rest_api", "async_handlers", "openapi"],
        defaultConfig: { framework: "fastapi" },
        baseWeights: BW.backendApi,
    },
    {
        type: "django_backend",
        category: "backend",
        subcategory: "API Services",
        label: "Django Backend",
        provider: "python",
        icon: "Server",
        description: "Full-featured Python backend with admin and ORM",
        tags: ["python", "orm", "public_api"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["rest_api", "admin_panel", "orm"],
        defaultConfig: { framework: "django" },
        baseWeights: BW.backendComplex,
    },
    {
        type: "rails_backend",
        category: "backend",
        subcategory: "API Services",
        label: "Ruby on Rails API",
        provider: "rails",
        icon: "Server",
        description: "Convention-driven web and API backend",
        tags: ["ruby", "mvc", "public_api"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["rest_api", "orm", "background_jobs"],
        defaultConfig: { framework: "rails" },
        baseWeights: BW.backendComplex,
    },
    {
        type: "go_backend",
        category: "backend",
        subcategory: "API Services",
        label: "Go Backend",
        provider: "golang",
        icon: "Server",
        description: "Compiled backend service for high throughput APIs",
        tags: ["go", "rest", "public_api"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["rest_api", "concurrency", "microservices"],
        defaultConfig: { language: "go" },
        baseWeights: BW.backendComplex,
    },
    {
        type: "spring_boot_backend",
        category: "backend",
        subcategory: "API Services",
        label: "Spring Boot Backend",
        provider: "java",
        icon: "Server",
        description: "Enterprise Java backend for robust services",
        tags: ["java", "enterprise", "public_api"],
        complexityHint: 4,
        costHint: "Medium",
        capabilities: ["rest_api", "dependency_injection", "microservices"],
        defaultConfig: { framework: "spring-boot" },
        baseWeights: BW.backendComplex,
    },
    {
        type: "dotnet_backend",
        category: "backend",
        subcategory: "API Services",
        label: ".NET Backend",
        provider: "microsoft",
        icon: "Server",
        description: "ASP.NET Core service backend",
        tags: ["dotnet", "enterprise", "public_api"],
        complexityHint: 3,
        costHint: "Medium",
        capabilities: ["rest_api", "grpc", "background_jobs"],
        defaultConfig: { framework: "aspnet-core" },
        baseWeights: BW.backendComplex,
    },
    {
        type: "serverless_functions",
        category: "backend",
        subcategory: "Serverless",
        label: "Serverless Functions",
        provider: "aws/gcp/azure",
        icon: "Network",
        description: "Event-driven functions for APIs and background tasks",
        tags: ["serverless", "functions", "public_api"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["event_handlers", "http_functions", "auto_scaling"],
        defaultConfig: { runtime: "node" },
        baseWeights: BW.backendManaged,
    },
    {
        type: "edge_functions",
        category: "backend",
        subcategory: "Serverless",
        label: "Edge Functions",
        provider: "vercel/cloudflare",
        icon: "Network",
        description: "Low-latency functions running close to users",
        tags: ["edge", "serverless", "public_api"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["edge_compute", "geo_routing", "low_latency"],
        defaultConfig: { runtime: "edge" },
        baseWeights: BW.backendManaged,
    },
    {
        type: "api_gateway",
        category: "backend",
        subcategory: "API Management",
        label: "API Gateway",
        provider: "aws/apigee/kong",
        icon: "Network",
        description: "Gateway for routing, auth, and policy enforcement",
        tags: ["gateway", "public_api", "edge"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["routing", "auth_proxy", "throttling"],
        defaultConfig: {},
        baseWeights: BW.backendComplex,
    },
    {
        type: "graphql_api",
        category: "backend",
        subcategory: "API Management",
        label: "GraphQL API",
        provider: "apollo/hasura",
        icon: "Network",
        description: "Single GraphQL endpoint for flexible client queries",
        tags: ["graphql", "public_api"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["graphql", "schema_federation", "typed_queries"],
        defaultConfig: { schema: "code-first" },
        baseWeights: BW.backendComplex,
    },
    {
        type: "bff_layer",
        category: "backend",
        subcategory: "API Management",
        label: "BFF Layer",
        provider: "generic",
        icon: "Network",
        description: "Backend-for-frontend layer for tailored client APIs",
        tags: ["bff", "api_aggregation", "public_api"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["api_aggregation", "orchestration", "client_specific_endpoints"],
        defaultConfig: {},
        baseWeights: BW.backendComplex,
    },
    {
        type: "worker",
        category: "backend",
        subcategory: "Async Processing",
        label: "Worker / Job Runner",
        provider: "generic",
        icon: "Cog",
        description: "Background processor for long-running or retryable tasks",
        tags: ["async", "jobs", "worker"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["async_processing", "retries", "scheduling"],
        defaultConfig: {},
        baseWeights: BW.backendComplex,
    },
    {
        type: "webhook_processor",
        category: "backend",
        subcategory: "Async Processing",
        label: "Webhook Processor",
        provider: "generic",
        icon: "ExternalLink",
        description: "Dedicated service for inbound webhook validation and processing",
        tags: ["webhooks", "integrations", "async"],
        complexityHint: 2,
        costHint: "Low",
        capabilities: ["webhook_ingest", "signature_verification", "retries"],
        defaultConfig: {},
        baseWeights: BW.backendApi,
    },
    {
        type: "external_api",
        category: "backend",
        subcategory: "Integrations",
        label: "External API",
        provider: "third-party",
        icon: "ExternalLink",
        description: "Third-party integration such as Stripe, Twilio, Maps, or CRM",
        tags: ["integration", "third_party"],
        complexityHint: 2,
        costHint: "Varies",
        capabilities: ["external_data", "webhooks", "payments"],
        defaultConfig: { service: "" },
        baseWeights: BW.backendApi,
    },
    {
        type: "twilio",
        category: "backend",
        subcategory: "Integrations",
        label: "Twilio",
        provider: "twilio",
        icon: "ExternalLink",
        description: "Programmable SMS, voice, WhatsApp, and communication workflows",
        tags: ["integration", "communications", "third_party"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["sms", "voice", "whatsapp", "otp"],
        defaultConfig: { channels: ["sms"] },
        baseWeights: BW.backendApi,
    },
    {
        type: "resend",
        category: "backend",
        subcategory: "Integrations",
        label: "Resend",
        provider: "resend",
        icon: "ExternalLink",
        description: "Developer-friendly transactional email delivery API",
        tags: ["integration", "email", "third_party"],
        complexityHint: 1,
        costHint: "Low",
        capabilities: ["transactional_email", "templates", "event_webhooks"],
        defaultConfig: { mode: "transactional" },
        baseWeights: BW.backendApi,
    },
    {
        type: "sendgrid",
        category: "backend",
        subcategory: "Integrations",
        label: "SendGrid",
        provider: "twilio",
        icon: "ExternalLink",
        description: "Email API for transactional and marketing email at scale",
        tags: ["integration", "email", "third_party"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["transactional_email", "bulk_email", "deliverability"],
        defaultConfig: { mode: "transactional" },
        baseWeights: BW.backendApi,
    },
    {
        type: "postmark",
        category: "backend",
        subcategory: "Integrations",
        label: "Postmark",
        provider: "activecampaign",
        icon: "ExternalLink",
        description: "Fast transactional email delivery with strong deliverability focus",
        tags: ["integration", "email", "third_party"],
        complexityHint: 1,
        costHint: "Low",
        capabilities: ["transactional_email", "inbound_email", "event_webhooks"],
        defaultConfig: { mode: "transactional" },
        baseWeights: BW.backendApi,
    },
    {
        type: "mailgun",
        category: "backend",
        subcategory: "Integrations",
        label: "Mailgun",
        provider: "sinch",
        icon: "ExternalLink",
        description: "Email sending and validation API for app notifications and campaigns",
        tags: ["integration", "email", "third_party"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["transactional_email", "email_validation", "event_webhooks"],
        defaultConfig: { mode: "transactional" },
        baseWeights: BW.backendApi,
    },
    {
        type: "stripe",
        category: "backend",
        subcategory: "Integrations",
        label: "Stripe",
        provider: "stripe",
        icon: "ExternalLink",
        description: "Payments, subscriptions, checkout, billing, and invoicing APIs",
        tags: ["integration", "payments", "billing"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["payments", "subscriptions", "checkout", "webhooks"],
        defaultConfig: { mode: "subscriptions" },
        baseWeights: BW.backendApi,
    },
    {
        type: "paddle",
        category: "backend",
        subcategory: "Integrations",
        label: "Paddle",
        provider: "paddle",
        icon: "ExternalLink",
        description: "Merchant-of-record billing and subscription platform for SaaS",
        tags: ["integration", "payments", "subscriptions"],
        complexityHint: 2,
        costHint: "Medium",
        capabilities: ["subscriptions", "merchant_of_record", "invoicing"],
        defaultConfig: { mode: "subscriptions" },
        baseWeights: BW.backendApi,
    },
    {
        type: "paypal",
        category: "backend",
        subcategory: "Integrations",
        label: "PayPal",
        provider: "paypal",
        icon: "ExternalLink",
        description: "Global payment acceptance for checkout and payouts",
        tags: ["integration", "payments", "third_party"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["payments", "checkout", "payouts"],
        defaultConfig: {},
        baseWeights: BW.backendApi,
    },
    {
        type: "plaid",
        category: "backend",
        subcategory: "Integrations",
        label: "Plaid",
        provider: "plaid",
        icon: "ExternalLink",
        description: "Financial data APIs for account linking and transaction insights",
        tags: ["integration", "fintech", "third_party"],
        complexityHint: 3,
        costHint: "Medium",
        capabilities: ["bank_linking", "transactions", "identity_verification"],
        defaultConfig: {},
        baseWeights: BW.backendApi,
    },
    {
        type: "segment",
        category: "backend",
        subcategory: "Integrations",
        label: "Segment",
        provider: "twilio",
        icon: "ExternalLink",
        description: "Customer data platform for event routing and analytics destinations",
        tags: ["integration", "analytics", "cdp"],
        complexityHint: 2,
        costHint: "Medium",
        capabilities: ["event_routing", "customer_profiles", "analytics_destinations"],
        defaultConfig: {},
        baseWeights: BW.backendApi,
    },
    {
        type: "slack_api",
        category: "backend",
        subcategory: "Integrations",
        label: "Slack API",
        provider: "slack",
        icon: "ExternalLink",
        description: "Notifications, bot commands, and workflow messaging integration",
        tags: ["integration", "notifications", "collaboration"],
        complexityHint: 1,
        costHint: "Low",
        capabilities: ["alerts", "bot_commands", "chat_ops"],
        defaultConfig: { mode: "notifications" },
        baseWeights: BW.backendApi,
    },
    {
        type: "salesforce",
        category: "backend",
        subcategory: "Integrations",
        label: "Salesforce",
        provider: "salesforce",
        icon: "ExternalLink",
        description: "CRM integration for leads, contacts, accounts, and workflows",
        tags: ["integration", "crm", "enterprise"],
        complexityHint: 3,
        costHint: "Medium-High",
        capabilities: ["crm_sync", "lead_management", "enterprise_workflows"],
        defaultConfig: {},
        baseWeights: BW.backendApi,
    },
    {
        type: "hubspot",
        category: "backend",
        subcategory: "Integrations",
        label: "HubSpot",
        provider: "hubspot",
        icon: "ExternalLink",
        description: "CRM and marketing automation integration for growth teams",
        tags: ["integration", "crm", "marketing"],
        complexityHint: 2,
        costHint: "Medium",
        capabilities: ["crm_sync", "marketing_automation", "email_workflows"],
        defaultConfig: {},
        baseWeights: BW.backendApi,
    },
    {
        type: "shopify_api",
        category: "backend",
        subcategory: "Integrations",
        label: "Shopify API",
        provider: "shopify",
        icon: "ExternalLink",
        description: "Ecommerce integration for products, orders, inventory, and storefront data",
        tags: ["integration", "ecommerce", "third_party"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["catalog_sync", "order_sync", "inventory_events"],
        defaultConfig: {},
        baseWeights: BW.backendApi,
    },

    // Data
    {
        type: "convex_db",
        category: "data",
        subcategory: "Operational Databases",
        label: "Convex Database",
        provider: "convex",
        icon: "Database",
        description: "Reactive document database with transactions and subscriptions",
        tags: ["document_db", "managed", "realtime"],
        complexityHint: 1,
        costHint: "Free-Low",
        capabilities: ["transactions", "reactive_queries", "indexes"],
        defaultConfig: { type: "document" },
        baseWeights: BW.dataManaged,
    },
    {
        type: "postgres",
        category: "data",
        subcategory: "Operational Databases",
        label: "PostgreSQL",
        provider: "neon/supabase/rds",
        icon: "Database",
        description: "General-purpose relational database",
        tags: ["sql", "relational", "oltp"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["sql", "transactions", "joins"],
        defaultConfig: { managed: true },
        baseWeights: BW.dataRelational,
    },
    {
        type: "mysql",
        category: "data",
        subcategory: "Operational Databases",
        label: "MySQL",
        provider: "planetScale/rds",
        icon: "Database",
        description: "Widely used relational database for transactional workloads",
        tags: ["sql", "relational", "oltp"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["sql", "transactions", "replication"],
        defaultConfig: { managed: true },
        baseWeights: BW.dataRelational,
    },
    {
        type: "mongodb",
        category: "data",
        subcategory: "Operational Databases",
        label: "MongoDB",
        provider: "mongodb atlas",
        icon: "Database",
        description: "Document database for flexible schemas",
        tags: ["nosql", "document_db"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["document_storage", "indexes", "aggregation"],
        defaultConfig: { managed: true },
        baseWeights: BW.dataManaged,
    },
    {
        type: "firestore",
        category: "data",
        subcategory: "Operational Databases",
        label: "Firestore",
        provider: "google",
        icon: "Database",
        description: "Managed NoSQL document database with realtime subscriptions",
        tags: ["nosql", "document_db", "realtime"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["document_storage", "realtime_subscriptions", "offline_sync"],
        defaultConfig: {},
        baseWeights: BW.dataManaged,
    },
    {
        type: "dynamodb",
        category: "data",
        subcategory: "Operational Databases",
        label: "DynamoDB",
        provider: "aws",
        icon: "Database",
        description: "Managed key-value/document store for high scale workloads",
        tags: ["nosql", "key_value", "managed"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["key_value", "auto_scaling", "ttl"],
        defaultConfig: {},
        baseWeights: BW.dataManaged,
    },
    {
        type: "redis",
        category: "data",
        subcategory: "Caching",
        label: "Redis Cache",
        provider: "redis",
        icon: "Zap",
        description: "In-memory cache, pub/sub, and ephemeral state store",
        tags: ["cache_layer", "in_memory", "pub_sub"],
        complexityHint: 2,
        costHint: "Low",
        capabilities: ["caching", "rate_limiting", "sessions"],
        defaultConfig: { managed: true },
        baseWeights: BW.cache,
    },
    {
        type: "upstash_redis",
        category: "data",
        subcategory: "Caching",
        label: "Upstash Redis",
        provider: "upstash",
        icon: "Zap",
        description: "Serverless Redis with pay-per-request pricing",
        tags: ["cache_layer", "in_memory", "serverless"],
        complexityHint: 1,
        costHint: "Low",
        capabilities: ["caching", "rate_limiting", "global_redis"],
        defaultConfig: {},
        baseWeights: BW.cache,
    },
    {
        type: "elasticsearch",
        category: "data",
        subcategory: "Search & Analytics",
        label: "Elasticsearch / OpenSearch",
        provider: "elastic/aws",
        icon: "Layers",
        description: "Search and analytics engine for full-text and faceted queries",
        tags: ["search", "full_text", "analytics"],
        complexityHint: 4,
        costHint: "Medium",
        capabilities: ["full_text_search", "aggregations", "facets"],
        defaultConfig: {},
        baseWeights: BW.backendComplex,
    },
    {
        type: "clickhouse",
        category: "data",
        subcategory: "Search & Analytics",
        label: "ClickHouse",
        provider: "clickhouse",
        icon: "Database",
        description: "Columnar analytics database for high-volume events",
        tags: ["analytics", "olap", "columnar"],
        complexityHint: 4,
        costHint: "Medium",
        capabilities: ["event_analytics", "columnar_queries", "large_scale_ingest"],
        defaultConfig: {},
        baseWeights: BW.backendComplex,
    },
    {
        type: "vector_db",
        category: "data",
        subcategory: "AI Data",
        label: "Vector Database",
        provider: "pinecone/weaviate/qdrant",
        icon: "Layers",
        description: "Embeddings storage and similarity search",
        tags: ["ai_data", "vector", "semantic_search"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["vector_search", "semantic_retrieval", "nearest_neighbor"],
        defaultConfig: {},
        baseWeights: { ...BW.aiSupport, aiReadiness: 3 },
    },
    {
        type: "snowflake_warehouse",
        category: "data",
        subcategory: "Warehousing",
        label: "Data Warehouse",
        provider: "snowflake/bigquery/redshift",
        icon: "Database",
        description: "Warehouse for business intelligence and analytics",
        tags: ["warehouse", "bi", "analytics"],
        complexityHint: 4,
        costHint: "Medium-High",
        capabilities: ["etl", "reporting", "historical_analytics"],
        defaultConfig: {},
        baseWeights: BW.backendComplex,
    },

    // Auth
    {
        type: "clerk_auth",
        category: "auth",
        subcategory: "Managed Identity",
        label: "Clerk",
        provider: "clerk",
        icon: "Shield",
        description: "Drop-in authentication and user management",
        tags: ["auth", "managed_identity"],
        complexityHint: 1,
        costHint: "Free-Low",
        capabilities: ["social_login", "mfa", "rbac"],
        defaultConfig: { socialLogin: true },
        baseWeights: BW.authManaged,
    },
    {
        type: "auth0",
        category: "auth",
        subcategory: "Managed Identity",
        label: "Auth0",
        provider: "okta",
        icon: "Shield",
        description: "Enterprise identity and access management",
        tags: ["auth", "managed_identity", "enterprise"],
        complexityHint: 2,
        costHint: "Free-Medium",
        capabilities: ["social_login", "sso", "mfa", "rbac"],
        defaultConfig: {},
        baseWeights: BW.authEnterprise,
    },
    {
        type: "supabase_auth",
        category: "auth",
        subcategory: "Managed Identity",
        label: "Supabase Auth",
        provider: "supabase",
        icon: "Shield",
        description: "Auth service with row-level policies and social providers",
        tags: ["auth", "managed_identity"],
        complexityHint: 1,
        costHint: "Free-Low",
        capabilities: ["social_login", "email_password", "jwt"],
        defaultConfig: {},
        baseWeights: BW.authManaged,
    },
    {
        type: "firebase_auth",
        category: "auth",
        subcategory: "Managed Identity",
        label: "Firebase Auth",
        provider: "google",
        icon: "Shield",
        description: "Managed auth with social and phone sign-in",
        tags: ["auth", "managed_identity"],
        complexityHint: 1,
        costHint: "Free-Low",
        capabilities: ["social_login", "phone_auth", "jwt"],
        defaultConfig: {},
        baseWeights: BW.authManaged,
    },
    {
        type: "cognito_auth",
        category: "auth",
        subcategory: "Managed Identity",
        label: "AWS Cognito",
        provider: "aws",
        icon: "Shield",
        description: "User pools and identity federation on AWS",
        tags: ["auth", "managed_identity", "enterprise"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["mfa", "federation", "jwt"],
        defaultConfig: {},
        baseWeights: BW.authEnterprise,
    },
    {
        type: "keycloak_auth",
        category: "auth",
        subcategory: "Self-Hosted Identity",
        label: "Keycloak",
        provider: "keycloak",
        icon: "Shield",
        description: "Self-hosted identity provider with SSO and realms",
        tags: ["auth", "self_hosted", "enterprise"],
        complexityHint: 4,
        costHint: "Low",
        capabilities: ["sso", "mfa", "rbac", "federation"],
        defaultConfig: {},
        baseWeights: BW.authEnterprise,
    },
    {
        type: "better_auth",
        category: "auth",
        subcategory: "Code-First Auth",
        label: "Better Auth",
        provider: "better-auth",
        icon: "Lock",
        description: "Code-first authentication library for app-owned auth flows",
        tags: ["auth", "code_first"],
        complexityHint: 3,
        costHint: "Low",
        capabilities: ["email_password", "oauth", "sessions"],
        defaultConfig: {},
        baseWeights: BW.backendApi,
    },
    {
        type: "custom_auth",
        category: "auth",
        subcategory: "Code-First Auth",
        label: "Custom Auth",
        provider: "custom",
        icon: "Lock",
        description: "Fully custom authentication implementation",
        tags: ["auth", "custom"],
        complexityHint: 5,
        costHint: "Low",
        capabilities: ["full_control"],
        defaultConfig: {},
        baseWeights: { buildSpeed: -3, complexity: 3, scalability: 0, opsBurden: 3, cost: -1, lockIn: -1, reliability: -1, aiReadiness: 0 },
    },

    // Storage
    {
        type: "convex_storage",
        category: "storage",
        subcategory: "Object Storage",
        label: "Convex File Storage",
        provider: "convex",
        icon: "HardDrive",
        description: "Managed file storage tied to Convex functions",
        tags: ["files", "file_uploads", "managed"],
        complexityHint: 1,
        costHint: "Free-Low",
        capabilities: ["file_upload", "signed_urls", "access_control"],
        defaultConfig: {},
        baseWeights: BW.storageManaged,
    },
    {
        type: "s3_r2",
        category: "storage",
        subcategory: "Object Storage",
        label: "S3 / Cloudflare R2",
        provider: "aws/cloudflare",
        icon: "HardDrive",
        description: "Durable object storage for media and documents",
        tags: ["files", "object_storage", "file_uploads"],
        complexityHint: 2,
        costHint: "Low",
        capabilities: ["file_upload", "presigned_urls", "lifecycle_rules"],
        defaultConfig: {},
        baseWeights: BW.storageManaged,
    },
    {
        type: "gcs_storage",
        category: "storage",
        subcategory: "Object Storage",
        label: "Google Cloud Storage",
        provider: "google",
        icon: "HardDrive",
        description: "Object storage on Google Cloud",
        tags: ["files", "object_storage", "file_uploads"],
        complexityHint: 2,
        costHint: "Low",
        capabilities: ["file_upload", "signed_urls", "lifecycle_rules"],
        defaultConfig: {},
        baseWeights: BW.storageManaged,
    },
    {
        type: "azure_blob_storage",
        category: "storage",
        subcategory: "Object Storage",
        label: "Azure Blob Storage",
        provider: "azure",
        icon: "HardDrive",
        description: "Blob/object storage on Azure",
        tags: ["files", "object_storage", "file_uploads"],
        complexityHint: 2,
        costHint: "Low",
        capabilities: ["file_upload", "signed_urls", "archive_tiers"],
        defaultConfig: {},
        baseWeights: BW.storageManaged,
    },
    {
        type: "supabase_storage",
        category: "storage",
        subcategory: "Object Storage",
        label: "Supabase Storage",
        provider: "supabase",
        icon: "HardDrive",
        description: "Managed object storage integrated with Supabase auth",
        tags: ["files", "object_storage", "file_uploads"],
        complexityHint: 1,
        costHint: "Free-Low",
        capabilities: ["file_upload", "access_control", "signed_urls"],
        defaultConfig: {},
        baseWeights: BW.storageManaged,
    },
    {
        type: "cloudinary",
        category: "storage",
        subcategory: "Media",
        label: "Cloudinary",
        provider: "cloudinary",
        icon: "HardDrive",
        description: "Media storage and transformation pipeline",
        tags: ["files", "media", "image_video"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["image_transform", "video_transform", "cdn_delivery"],
        defaultConfig: {},
        baseWeights: BW.storageManaged,
    },
    {
        type: "uploadthing",
        category: "storage",
        subcategory: "Media",
        label: "UploadThing",
        provider: "uploadthing",
        icon: "HardDrive",
        description: "Developer-friendly file upload workflow",
        tags: ["files", "file_uploads", "frontend_integration"],
        complexityHint: 1,
        costHint: "Low",
        capabilities: ["file_upload", "upload_callbacks", "typed_routes"],
        defaultConfig: {},
        baseWeights: BW.storageManaged,
    },

    // AI
    {
        type: "llm_provider",
        category: "ai",
        subcategory: "LLM APIs",
        label: "Generic LLM Provider",
        provider: "openai/google/anthropic",
        icon: "Brain",
        description: "Abstract LLM component when vendor choice is undecided",
        tags: ["ai", "llm", "generation"],
        complexityHint: 2,
        costHint: "Medium-High",
        capabilities: ["chat", "text_generation", "structured_output"],
        defaultConfig: { model: "fast" },
        baseWeights: BW.aiCore,
    },
    {
        type: "openai_llm",
        category: "ai",
        subcategory: "LLM APIs",
        label: "OpenAI",
        provider: "openai",
        icon: "Brain",
        description: "OpenAI models for chat, reasoning, and multimodal tasks",
        tags: ["ai", "llm", "generation"],
        complexityHint: 2,
        costHint: "Medium-High",
        capabilities: ["chat", "structured_output", "tool_calling", "embeddings"],
        defaultConfig: { model: "gpt-4.1-mini" },
        baseWeights: BW.aiCore,
    },
    {
        type: "anthropic_llm",
        category: "ai",
        subcategory: "LLM APIs",
        label: "Anthropic",
        provider: "anthropic",
        icon: "Brain",
        description: "Anthropic Claude models for assistant and workflow tasks",
        tags: ["ai", "llm", "generation"],
        complexityHint: 2,
        costHint: "Medium-High",
        capabilities: ["chat", "long_context", "tool_calling"],
        defaultConfig: { model: "claude-sonnet" },
        baseWeights: BW.aiCore,
    },
    {
        type: "gemini_llm",
        category: "ai",
        subcategory: "LLM APIs",
        label: "Google Gemini",
        provider: "google",
        icon: "Brain",
        description: "Gemini models for chat, multimodal, and tool-driven tasks",
        tags: ["ai", "llm", "generation"],
        complexityHint: 2,
        costHint: "Medium",
        capabilities: ["chat", "multimodal", "tool_calling", "embeddings"],
        defaultConfig: { model: "gemini-3-flash-preview" },
        baseWeights: BW.aiCore,
    },
    {
        type: "embeddings_provider",
        category: "ai",
        subcategory: "Retrieval",
        label: "Embeddings Provider",
        provider: "openai/google/cohere",
        icon: "Layers",
        description: "Text and document embeddings for semantic retrieval",
        tags: ["ai", "embeddings", "retrieval"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["text_embeddings", "chunk_embeddings"],
        defaultConfig: {},
        baseWeights: BW.aiSupport,
    },
    {
        type: "reranker",
        category: "ai",
        subcategory: "Retrieval",
        label: "Reranker",
        provider: "cohere/voyage",
        icon: "Layers",
        description: "Re-ranks retrieved context to improve answer quality",
        tags: ["ai", "retrieval", "ranking"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["rerank_results", "relevance_scoring"],
        defaultConfig: {},
        baseWeights: BW.aiSupport,
    },
    {
        type: "moderation",
        category: "ai",
        subcategory: "Safety",
        label: "Moderation",
        provider: "openai/azure/google",
        icon: "ShieldCheck",
        description: "Moderation service for user-generated or model-generated content",
        tags: ["ai", "safety", "moderation"],
        complexityHint: 2,
        costHint: "Low",
        capabilities: ["content_moderation", "policy_checks"],
        defaultConfig: {},
        baseWeights: BW.aiSupport,
    },
    {
        type: "speech_to_text",
        category: "ai",
        subcategory: "Multimodal",
        label: "Speech to Text",
        provider: "openai/google/assemblyai",
        icon: "Brain",
        description: "Automatic speech recognition for audio input",
        tags: ["ai", "speech", "audio"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["transcription", "speaker_diarization"],
        defaultConfig: {},
        baseWeights: BW.aiSupport,
    },
    {
        type: "text_to_speech",
        category: "ai",
        subcategory: "Multimodal",
        label: "Text to Speech",
        provider: "elevenlabs/google/openai",
        icon: "Brain",
        description: "Voice synthesis for conversational and accessibility features",
        tags: ["ai", "speech", "audio"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["voice_generation", "streaming_audio"],
        defaultConfig: {},
        baseWeights: BW.aiSupport,
    },
    {
        type: "image_generation",
        category: "ai",
        subcategory: "Multimodal",
        label: "Image Generation",
        provider: "openai/stability/google",
        icon: "Brain",
        description: "Text-to-image generation component",
        tags: ["ai", "image", "generation"],
        complexityHint: 2,
        costHint: "Medium",
        capabilities: ["text_to_image", "image_editing"],
        defaultConfig: {},
        baseWeights: BW.aiSupport,
    },
    {
        type: "ai_agent_framework",
        category: "ai",
        subcategory: "Agent Orchestration",
        label: "Agent Framework",
        provider: "langgraph/crewai",
        icon: "Brain",
        description: "Multi-step agent orchestration with tools and memory",
        tags: ["ai", "agents", "workflow"],
        complexityHint: 4,
        costHint: "Medium-High",
        capabilities: ["agent_loops", "tool_use", "memory"],
        defaultConfig: {},
        baseWeights: { ...BW.aiCore, complexity: 2, opsBurden: 1 },
    },
    {
        type: "ai_gateway",
        category: "ai",
        subcategory: "Agent Orchestration",
        label: "AI Gateway",
        provider: "portkey/openrouter",
        icon: "Network",
        description: "Routing, fallback, and policy controls across model providers",
        tags: ["ai", "llm", "gateway"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["provider_routing", "fallbacks", "prompt_logging"],
        defaultConfig: {},
        baseWeights: BW.aiSupport,
    },

    // Infrastructure
    {
        type: "queue",
        category: "infra",
        subcategory: "Async",
        label: "Message Queue",
        provider: "sqs/rabbitmq",
        icon: "List",
        description: "Queue for async background processing",
        tags: ["queue", "async", "retries"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["async_messaging", "retries", "dead_letter"],
        defaultConfig: {},
        baseWeights: BW.infraComplex,
    },
    {
        type: "event_bus",
        category: "infra",
        subcategory: "Async",
        label: "Event Bus",
        provider: "sns/pubsub/kafka",
        icon: "List",
        description: "Pub/sub backbone for decoupled event-driven systems",
        tags: ["queue", "pub_sub", "async"],
        complexityHint: 4,
        costHint: "Medium",
        capabilities: ["event_routing", "fanout", "pub_sub"],
        defaultConfig: {},
        baseWeights: BW.infraComplex,
    },
    {
        type: "scheduler",
        category: "infra",
        subcategory: "Automation",
        label: "Scheduler / Cron",
        provider: "cloud scheduler/cron",
        icon: "Clock",
        description: "Runs periodic jobs and maintenance tasks",
        tags: ["scheduler", "cron", "automation"],
        complexityHint: 2,
        costHint: "Free-Low",
        capabilities: ["periodic_jobs", "scheduled_tasks"],
        defaultConfig: {},
        baseWeights: BW.infraManaged,
    },
    {
        type: "workflow_orchestrator",
        category: "infra",
        subcategory: "Automation",
        label: "Workflow Orchestrator",
        provider: "temporal/inngest",
        icon: "Clock",
        description: "Durable multi-step workflow orchestration",
        tags: ["workflow", "durable_execution", "async"],
        complexityHint: 4,
        costHint: "Medium",
        capabilities: ["workflow_state", "retries", "sagas"],
        defaultConfig: {},
        baseWeights: BW.infraComplex,
    },
    {
        type: "websocket_realtime",
        category: "infra",
        subcategory: "Realtime",
        label: "Realtime / WebSocket",
        provider: "ably/pusher/socketio",
        icon: "Network",
        description: "Realtime messaging and presence updates",
        tags: ["realtime", "websocket", "pub_sub"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["websocket", "presence", "broadcast"],
        defaultConfig: {},
        baseWeights: BW.infraManaged,
    },
    {
        type: "cdn",
        category: "infra",
        subcategory: "Delivery",
        label: "CDN",
        provider: "cloudflare/fastly",
        icon: "Globe",
        description: "Global edge caching for static and media assets",
        tags: ["cdn_edge", "edge_cache", "performance"],
        complexityHint: 1,
        costHint: "Free-Low",
        capabilities: ["edge_delivery", "static_caching", "ddos_protection"],
        defaultConfig: {},
        baseWeights: BW.infraManaged,
    },
    {
        type: "load_balancer",
        category: "infra",
        subcategory: "Delivery",
        label: "Load Balancer",
        provider: "aws/gcp/azure",
        icon: "Network",
        description: "Distributes traffic across service instances",
        tags: ["networking", "high_availability"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["traffic_distribution", "health_checks", "ssl_termination"],
        defaultConfig: {},
        baseWeights: BW.infraComplex,
    },
    {
        type: "rate_limiter",
        category: "infra",
        subcategory: "Security",
        label: "Rate Limiter",
        provider: "cloudflare/upstash",
        icon: "Zap",
        description: "Protect APIs from abuse via token bucket or fixed window limits",
        tags: ["security", "rate_limiting", "public_api_guard"],
        complexityHint: 2,
        costHint: "Low",
        capabilities: ["rate_limiting", "abuse_protection"],
        defaultConfig: {},
        baseWeights: BW.infraManaged,
    },
    {
        type: "feature_flags",
        category: "infra",
        subcategory: "Product Operations",
        label: "Feature Flags",
        provider: "launchdarkly/posthog",
        icon: "List",
        description: "Feature rollout and experimentation controls",
        tags: ["flags", "experimentation"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["gradual_rollout", "a_b_testing"],
        defaultConfig: {},
        baseWeights: BW.infraManaged,
    },
    {
        type: "secrets_manager",
        category: "infra",
        subcategory: "Security",
        label: "Secrets Manager",
        provider: "aws/gcp/hashicorp",
        icon: "Lock",
        description: "Secure storage and rotation for credentials and API keys",
        tags: ["security", "secrets"],
        complexityHint: 2,
        costHint: "Low",
        capabilities: ["secret_storage", "secret_rotation", "audit_trail"],
        defaultConfig: {},
        baseWeights: BW.infraManaged,
    },

    // Deployment
    {
        type: "vercel_deploy",
        category: "deployment",
        subcategory: "Managed Platforms",
        label: "Vercel",
        provider: "vercel",
        icon: "Globe",
        description: "Managed web deployment platform optimized for frontend and edge",
        tags: ["deployment", "managed", "cdn_edge"],
        complexityHint: 1,
        costHint: "Free-Low",
        capabilities: ["preview_deployments", "edge_runtime", "cdn"],
        defaultConfig: {},
        baseWeights: BW.deployManaged,
    },
    {
        type: "netlify_deploy",
        category: "deployment",
        subcategory: "Managed Platforms",
        label: "Netlify",
        provider: "netlify",
        icon: "Globe",
        description: "Managed web hosting with forms, edge functions, and previews",
        tags: ["deployment", "managed", "cdn_edge"],
        complexityHint: 1,
        costHint: "Free-Low",
        capabilities: ["preview_deployments", "static_hosting", "edge_functions"],
        defaultConfig: {},
        baseWeights: BW.deployManaged,
    },
    {
        type: "cloudflare_workers",
        category: "deployment",
        subcategory: "Managed Platforms",
        label: "Cloudflare Workers",
        provider: "cloudflare",
        icon: "Globe",
        description: "Edge compute runtime for globally distributed services",
        tags: ["deployment", "edge", "cdn_edge"],
        complexityHint: 2,
        costHint: "Low",
        capabilities: ["edge_compute", "global_distribution"],
        defaultConfig: {},
        baseWeights: BW.deployManaged,
    },
    {
        type: "aws_lambda",
        category: "deployment",
        subcategory: "Serverless Deploy",
        label: "AWS Lambda",
        provider: "aws",
        icon: "Network",
        description: "Serverless compute platform for event-driven workloads",
        tags: ["deployment", "serverless"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["event_compute", "auto_scaling", "pay_per_use"],
        defaultConfig: {},
        baseWeights: BW.deployManaged,
    },
    {
        type: "aws_ecs",
        category: "deployment",
        subcategory: "Container Platforms",
        label: "AWS ECS/Fargate",
        provider: "aws",
        icon: "Network",
        description: "Managed container orchestration with autoscaling",
        tags: ["deployment", "containers"],
        complexityHint: 3,
        costHint: "Medium",
        capabilities: ["container_deploy", "autoscaling", "service_discovery"],
        defaultConfig: {},
        baseWeights: BW.deploySelfManaged,
    },
    {
        type: "kubernetes",
        category: "deployment",
        subcategory: "Container Platforms",
        label: "Kubernetes",
        provider: "eks/gke/aks",
        icon: "Network",
        description: "Highly flexible container orchestration platform",
        tags: ["deployment", "containers", "orchestration"],
        complexityHint: 5,
        costHint: "Medium-High",
        capabilities: ["container_orchestration", "autoscaling", "rolling_updates"],
        defaultConfig: {},
        baseWeights: BW.deploySelfManaged,
    },
    {
        type: "docker",
        category: "deployment",
        subcategory: "Container Platforms",
        label: "Docker",
        provider: "docker",
        icon: "Cog",
        description: "Container packaging and runtime foundation",
        tags: ["deployment", "containers"],
        complexityHint: 2,
        costHint: "Free-Low",
        capabilities: ["containerization", "local_parity"],
        defaultConfig: {},
        baseWeights: BW.deploySelfManaged,
    },
    {
        type: "github_actions",
        category: "deployment",
        subcategory: "CI/CD",
        label: "GitHub Actions",
        provider: "github",
        icon: "Cog",
        description: "CI/CD automation for testing and deployments",
        tags: ["deployment", "cicd", "automation"],
        complexityHint: 2,
        costHint: "Free-Low",
        capabilities: ["build_pipeline", "test_automation", "deploy_automation"],
        defaultConfig: {},
        baseWeights: BW.deployManaged,
    },
    {
        type: "terraform_iac",
        category: "deployment",
        subcategory: "Infrastructure as Code",
        label: "Terraform",
        provider: "hashicorp",
        icon: "Cog",
        description: "Declarative infrastructure provisioning",
        tags: ["deployment", "iac", "automation"],
        complexityHint: 4,
        costHint: "Low",
        capabilities: ["infrastructure_provisioning", "state_management"],
        defaultConfig: {},
        baseWeights: BW.deploySelfManaged,
    },
    {
        type: "cloud_run",
        category: "deployment",
        subcategory: "Serverless Deploy",
        label: "Cloud Run",
        provider: "google",
        icon: "Network",
        description: "Serverless container deployment with automatic scaling",
        tags: ["deployment", "serverless", "containers"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["container_deploy", "auto_scaling", "http_services"],
        defaultConfig: {},
        baseWeights: BW.deployManaged,
    },

    // Observability
    {
        type: "monitoring",
        category: "observability",
        subcategory: "Core",
        label: "Monitoring",
        provider: "datadog/newrelic",
        icon: "Activity",
        description: "Metrics, dashboards, and uptime monitoring",
        tags: ["observability", "metrics", "apm"],
        complexityHint: 2,
        costHint: "Free-Medium",
        capabilities: ["metrics", "apm", "alerts"],
        defaultConfig: {},
        baseWeights: BW.observabilityCore,
    },
    {
        type: "error_tracking",
        category: "observability",
        subcategory: "Core",
        label: "Error Tracking",
        provider: "sentry/bugsnag",
        icon: "Activity",
        description: "Exception tracking with stack traces and release context",
        tags: ["observability", "errors", "monitoring"],
        complexityHint: 1,
        costHint: "Free-Low",
        capabilities: ["error_alerting", "release_tracking"],
        defaultConfig: {},
        baseWeights: BW.observabilityCore,
    },
    {
        type: "logging_stack",
        category: "observability",
        subcategory: "Core",
        label: "Centralized Logging",
        provider: "elk/loki",
        icon: "Activity",
        description: "Log aggregation and search across services",
        tags: ["observability", "logging"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["log_aggregation", "log_search", "retention"],
        defaultConfig: {},
        baseWeights: BW.observabilityAdvanced,
    },
    {
        type: "tracing",
        category: "observability",
        subcategory: "Core",
        label: "Distributed Tracing",
        provider: "opentelemetry/jaeger",
        icon: "Activity",
        description: "Request-level traces across distributed systems",
        tags: ["observability", "tracing", "apm"],
        complexityHint: 3,
        costHint: "Low-Medium",
        capabilities: ["distributed_tracing", "latency_analysis"],
        defaultConfig: {},
        baseWeights: BW.observabilityAdvanced,
    },
    {
        type: "analytics",
        category: "observability",
        subcategory: "Product",
        label: "Analytics",
        provider: "ga4/plausible",
        icon: "BarChart3",
        description: "Traffic and usage analytics",
        tags: ["observability", "analytics", "product"],
        complexityHint: 1,
        costHint: "Free-Low",
        capabilities: ["traffic_analytics", "event_tracking"],
        defaultConfig: {},
        baseWeights: BW.observabilityCore,
    },
    {
        type: "product_analytics",
        category: "observability",
        subcategory: "Product",
        label: "Product Analytics",
        provider: "posthog/mixpanel/amplitude",
        icon: "BarChart3",
        description: "Behavior analytics, funnels, and experiments",
        tags: ["observability", "analytics", "product"],
        complexityHint: 2,
        costHint: "Low-Medium",
        capabilities: ["funnel_analysis", "cohort_analysis", "feature_analytics"],
        defaultConfig: {},
        baseWeights: BW.observabilityCore,
    },
    {
        type: "status_page",
        category: "observability",
        subcategory: "Operations",
        label: "Status Page",
        provider: "atlassian/instatus",
        icon: "BarChart3",
        description: "Public service health communication",
        tags: ["observability", "status", "incident_response"],
        complexityHint: 1,
        costHint: "Free-Low",
        capabilities: ["status_updates", "incident_comms"],
        defaultConfig: {},
        baseWeights: BW.observabilityCore,
    },
    {
        type: "incident_management",
        category: "observability",
        subcategory: "Operations",
        label: "Incident Management",
        provider: "pagerduty/opsgenie",
        icon: "Activity",
        description: "On-call scheduling and incident escalation",
        tags: ["observability", "incident_response", "alerts"],
        complexityHint: 2,
        costHint: "Medium",
        capabilities: ["on_call", "escalation_policies"],
        defaultConfig: {},
        baseWeights: BW.observabilityAdvanced,
    },
];

export function getComponentByType(type: string): ComponentDef | undefined {
    return COMPONENT_CATALOG.find((c) => c.type === type);
}

export function getComponentsByCategory(category: ComponentCategory): ComponentDef[] {
    return COMPONENT_CATALOG.filter((c) => c.category === category);
}
