interface GNode { id: string; data?: { label?: string; category?: string; componentId?: string } }
interface ScoreResult { overall: number; dimensions: Record<string, { score: number; explanation: string }> }

export function generatePRDMarkdown(
  projectName: string,
  description: string,
  nodes: GNode[],
  scores: ScoreResult | null,
  features: string[],
  constraints: Record<string, any>
): string {
  const techStack = nodes.map((n) => n.data?.label || "").filter(Boolean);
  const categories = [...new Set(nodes.map((n) => n.data?.category).filter(Boolean))];

  let md = `# ${projectName} — Architecture PRD\n\n`;
  md += `*Generated by Preflight*\n\n`;

  if (description) {
    md += `## Overview\n\n${description}\n\n`;
  }

  md += `## Tech Stack\n\n`;
  for (const tech of techStack) {
    md += `- ${tech}\n`;
  }
  md += "\n";

  md += `## Architecture Components\n\n`;
  md += `| Category | Component |\n|---|---|\n`;
  for (const node of nodes) {
    md += `| ${node.data?.category || "?"} | ${node.data?.label || "?"} |\n`;
  }
  md += "\n";

  if (scores) {
    md += `## Architecture Scores\n\n`;
    md += `**Overall: ${scores.overall.toFixed(1)} / 10**\n\n`;
    for (const [key, dim] of Object.entries(scores.dimensions)) {
      md += `- **${key}**: ${dim.score.toFixed(1)}/10 — ${dim.explanation}\n`;
    }
    md += "\n";
  }

  if (constraints && Object.keys(constraints).length > 0) {
    md += `## Constraints\n\n`;
    for (const [key, val] of Object.entries(constraints)) {
      if (Array.isArray(val) && val.length === 0) continue;
      md += `- **${key}**: ${JSON.stringify(val)}\n`;
    }
    md += "\n";
  }

  if (features.length > 0) {
    md += `## Planned Features\n\n`;
    for (const f of features) {
      md += `- [ ] ${f}\n`;
    }
    md += "\n";
  }

  md += `## Build Order\n\n`;
  md += `1. Project scaffold and configuration\n`;
  if (nodes.some((n) => n.data?.category === "database")) md += `2. Database setup and schema\n`;
  if (nodes.some((n) => n.data?.category === "auth")) md += `3. Authentication\n`;
  md += `4. Core business logic\n`;
  for (let i = 0; i < features.length; i++) {
    md += `${5 + i}. ${features[i]}\n`;
  }
  md += `${5 + features.length}. Testing and deployment\n`;

  md += `\n---\n*Plan before you build. Score before you ship.*\n`;

  return md;
}
