import { COMPONENT_LIBRARY, getComponentById } from "./components-data";

export interface ReportInput {
  selectedIds: string[];
  messages: { role: string; content: string }[];
  title?: string;
}

function getCategoryForComponent(componentId: string): string {
  for (const cat of COMPONENT_LIBRARY) {
    if (cat.components.some((c) => c.id === componentId)) return cat.name;
  }
  return "Other";
}

function stripComponentIdsLine(text: string): string {
  return text.replace(/\n?\s*COMPONENT_IDS:\s*[^\n]+/i, "").trim();
}

/** Build full report markdown: components visual (table), cost breakdown, optimization strategy. */
export function buildReportMarkdown(input: ReportInput): string {
  const { selectedIds, messages, title = "Architecture Report" } = input;
  const components = selectedIds
    .map((id) => getComponentById(id))
    .filter(Boolean) as Array<{ id: string; name: string; baseCost?: number; description?: string }>;
  const byCategory = new Map<string, typeof components>();
  for (const c of components) {
    const cat = getCategoryForComponent(c.id);
    if (!byCategory.has(cat)) byCategory.set(cat, []);
    byCategory.get(cat)!.push(c);
  }
  const totalCost = components.reduce((sum, c) => sum + (c.baseCost ?? 0), 0);
  const lastAssistant = [...messages].reverse().find((m) => m.role === "assistant");
  const strategyText = lastAssistant
    ? stripComponentIdsLine(lastAssistant.content).trim()
    : "Review your Preflight chat for recommendations and optimization tips.";

  let md = `# ${title}\n\n`;
  md += `*Generated by Preflight • ${new Date().toISOString().slice(0, 10)}*\n\n`;
  md += "---\n\n";

  md += "## Component overview\n\n";
  md += "| Category | Component | Est. monthly cost |\n";
  md += "|----------|-----------|--------------------|\n";
  for (const [cat, comps] of byCategory) {
    for (const c of comps) {
      const cost = c.baseCost && c.baseCost > 0 ? `$${c.baseCost}` : "Free tier";
      md += `| ${cat} | **${c.name}** | ${cost} |\n`;
    }
  }
  md += "\n";

  md += "## Cost summary\n\n";
  md += "| Item | Amount |\n|------|--------|\n";
  md += `| **Total estimated base cost** | **$${totalCost}/mo** |\n`;
  md += "\n*Base costs are approximate; usage-based services (e.g. APIs, storage) will add to this.*\n\n";

  md += "## Optimization & strategy\n\n";
  md += strategyText.split("\n").map((line) => line.trim()).filter(Boolean).join("\n\n") + "\n\n";

  md += "---\n\n*Preflight – Plan before you build.*\n";
  return md;
}

/** Build HTML for print/PDF: same content, print-friendly. */
export function buildReportHtml(input: ReportInput): string {
  const { selectedIds, messages, title = "Architecture Report" } = input;
  const components = selectedIds
    .map((id) => getComponentById(id))
    .filter(Boolean) as Array<{ id: string; name: string; baseCost?: number }>;
  const byCategory = new Map<string, typeof components>();
  for (const c of components) {
    const cat = getCategoryForComponent(c.id);
    if (!byCategory.has(cat)) byCategory.set(cat, []);
    byCategory.get(cat)!.push(c);
  }
  const totalCost = components.reduce((sum, c) => sum + (c.baseCost ?? 0), 0);
  const lastAssistant = [...messages].reverse().find((m) => m.role === "assistant");
  const strategyRaw = lastAssistant
    ? stripComponentIdsLine(lastAssistant.content).trim()
    : "Review your Preflight chat for recommendations and optimization tips.";
  const strategyText = strategyRaw
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\n/g, "<br/>");

  const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const rows = Array.from(byCategory.entries())
    .map(
      ([cat, comps]) =>
        comps
          .map(
            (c) =>
              `<tr><td>${esc(cat)}</td><td><strong>${esc(c.name)}</strong></td><td>${c.baseCost && c.baseCost > 0 ? `$${c.baseCost}` : "Free tier"}</td></tr>`
          )
          .join("")
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${esc(title)}</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 720px; margin: 2rem auto; padding: 1rem; color: #1a1a1a; line-height: 1.5; }
    h1 { font-size: 1.75rem; margin-bottom: 0.25rem; }
    .meta { color: #666; font-size: 0.875rem; margin-bottom: 1.5rem; }
    h2 { font-size: 1.15rem; margin-top: 1.5rem; margin-bottom: 0.5rem; border-bottom: 1px solid #eee; }
    table { width: 100%; border-collapse: collapse; margin: 0.5rem 0 1rem; }
    th, td { text-align: left; padding: 0.5rem 0.75rem; border-bottom: 1px solid #eee; }
    th { font-weight: 600; color: #444; }
    .strategy { background: #f8f9fa; padding: 1rem; border-radius: 8px; margin-top: 0.5rem; }
    .total { font-weight: 700; }
    @media print { body { margin: 0; padding: 1rem; } }
  </style>
</head>
<body>
  <h1>${esc(title)}</h1>
  <p class="meta">Generated by Preflight • ${new Date().toISOString().slice(0, 10)}</p>
  <hr/>
  <h2>Component overview</h2>
  <table>
    <thead><tr><th>Category</th><th>Component</th><th>Est. monthly cost</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <h2>Cost summary</h2>
  <table>
    <tr><td><strong>Total estimated base cost</strong></td><td class="total">$${totalCost}/mo</td></tr>
  </table>
  <p><em>Base costs are approximate; usage-based services will add to this.</em></p>
  <h2>Optimization & strategy</h2>
  <div class="strategy">${strategyText}</div>
  <hr/>
  <p><em>Preflight – Plan before you build.</em></p>
</body>
</html>`;
}
