"use client";

import React, { useState } from "react";
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { type ArchNode, type ArchEdge } from "@/lib/store";
import { Download, Copy, Check, FileJson, FileText, Loader2, Sparkles } from "lucide-react";

interface ExportModalProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    projectName: string;
    nodes: ArchNode[];
    edges: ArchEdge[];
    scores: Record<string, { score: number; explanation: string }> | null;
    lintIssues: Array<{
        code: string;
        severity: string;
        title: string;
        description: string;
        targets: string[];
        suggestedFix: string;
    }> | null;
}

export function ExportModal({
    open,
    onOpenChange,
    projectName,
    nodes,
    edges,
    scores,
    lintIssues,
}: ExportModalProps) {
    const [copied, setCopied] = useState<string | null>(null);
    const [isGeneratingPrompts, setIsGeneratingPrompts] = useState(false);

    const architectureJSON = {
        project: projectName,
        generatedAt: new Date().toISOString(),
        graph: {
            nodes: nodes.map((n) => ({
                id: n.id,
                type: n.data.type,
                category: n.data.category,
                label: n.data.label,
                provider: n.data.provider,
                tags: n.data.tags,
                config: n.data.config,
            })),
            edges: edges.map((e) => ({
                source: e.source,
                target: e.target,
                relationship: (e.data as { relationshipType?: string })?.relationshipType ?? "invokes",
                protocol: (e.data as { protocol?: string })?.protocol ?? "RPC",
            })),
        },
        scores,
        lintIssues,
    };

    const generateMarkdown = () => {
        let md = `# ${projectName} — Architecture Plan\n\n`;
        md += `*Generated by Preflight on ${new Date().toLocaleDateString()}*\n\n`;
        md += `## Architecture Overview\n\n`;
        md += `### Components (${nodes.length})\n\n`;

        const categories = [...new Set(nodes.map((n) => n.data.category))];
        for (const cat of categories) {
            const catNodes = nodes.filter((n) => n.data.category === cat);
            md += `#### ${cat.charAt(0).toUpperCase() + cat.slice(1)}\n\n`;
            for (const n of catNodes) {
                md += `- **${n.data.label}** (${n.data.provider}) — ${n.data.tags.join(", ")}\n`;
            }
            md += "\n";
        }

        md += `### Connections (${edges.length})\n\n`;
        for (const e of edges) {
            const source = nodes.find((n) => n.id === e.source);
            const target = nodes.find((n) => n.id === e.target);
            const rel = (e.data as { relationshipType?: string })?.relationshipType ?? "invokes";
            md += `- ${source?.data.label ?? e.source} → ${target?.data.label ?? e.target} (${rel})\n`;
        }

        if (scores && Object.keys(scores).length > 0) {
            md += `\n## Scores\n\n`;
            md += `| Dimension | Score | Assessment |\n|---|---|---|\n`;
            for (const [key, { score, explanation }] of Object.entries(scores)) {
                md += `| ${key} | ${score}/10 | ${explanation} |\n`;
            }
        }

        if (lintIssues && lintIssues.length > 0) {
            md += `\n## Lint Issues\n\n`;
            for (const issue of lintIssues) {
                const icon = issue.severity === "error" ? "🔴" : issue.severity === "warning" ? "🟡" : "🔵";
                md += `${icon} **${issue.title}** — ${issue.description}\n`;
                md += `   💡 *${issue.suggestedFix}*\n\n`;
            }
        }

        md += `\n## Prompt Pack\n\n`;
        md += `### 1. Project Setup\n\n`;
        md += "```\n";
        md += `Create a new project with the following architecture:\n`;
        md += `Stack: ${[...new Set(nodes.map((n) => n.data.provider))].join(", ")}\n`;
        md += `Components: ${nodes.map((n) => n.data.label).join(", ")}\n`;
        md += "```\n\n";

        md += `### 2. Implementation Order\n\n`;
        const order = ["auth", "data", "backend", "ai", "storage", "frontend", "infra"];
        let step = 1;
        for (const cat of order) {
            const catNodes = nodes.filter((n) => n.data.category === cat);
            if (catNodes.length > 0) {
                md += `${step}. **${cat.charAt(0).toUpperCase() + cat.slice(1)}**: ${catNodes.map((n) => n.data.label).join(", ")}\n`;
                step++;
            }
        }

        return md;
    };

    const handleCopy = async (content: string, type: string) => {
        await navigator.clipboard.writeText(content);
        setCopied(type);
        setTimeout(() => setCopied(null), 2000);
    };

    const handleDownload = (content: string, filename: string, mimeType: string) => {
        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = filename;
        a.click();
        URL.revokeObjectURL(url);
    };

    const handleGeneratePromptPack = async () => {
        setIsGeneratingPrompts(true);
        try {
            const response = await fetch("/api/export", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    projectName,
                    nodes: architectureJSON.graph.nodes,
                    edges: architectureJSON.graph.edges,
                    scores,
                }),
            });

            if (response.ok) {
                const data = await response.json();
                if (data.promptPack) {
                    handleDownload(data.promptPack, `${projectName}-prompt-pack.md`, "text/markdown");
                }
            }
        } catch (err) {
            console.error("Prompt pack generation failed:", err);
        } finally {
            setIsGeneratingPrompts(false);
        }
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-md">
                <DialogHeader>
                    <DialogTitle className="flex items-center gap-2">
                        <Download className="h-5 w-5 text-primary" />
                        Export Architecture
                    </DialogTitle>
                </DialogHeader>

                <div className="space-y-3 py-2">
                    {/* JSON Export */}
                    <div className="p-3 rounded-lg border border-border hover:border-primary/30 transition-colors">
                        <div className="flex items-center justify-between">
                            <div className="flex items-center gap-2">
                                <FileJson className="h-4 w-4 text-blue-400" />
                                <div>
                                    <p className="text-sm font-medium">Architecture JSON</p>
                                    <p className="text-[10px] text-muted-foreground">
                                        Full graph with nodes, edges, scores, and lint issues
                                    </p>
                                </div>
                            </div>
                            <div className="flex gap-1">
                                <Button
                                    variant="ghost"
                                    size="sm"
                                    className="h-7 text-xs"
                                    onClick={() =>
                                        handleCopy(JSON.stringify(architectureJSON, null, 2), "json")
                                    }
                                >
                                    {copied === "json" ? (
                                        <Check className="h-3 w-3" />
                                    ) : (
                                        <Copy className="h-3 w-3" />
                                    )}
                                </Button>
                                <Button
                                    variant="ghost"
                                    size="sm"
                                    className="h-7 text-xs"
                                    onClick={() =>
                                        handleDownload(
                                            JSON.stringify(architectureJSON, null, 2),
                                            `${projectName}-architecture.json`,
                                            "application/json"
                                        )
                                    }
                                >
                                    <Download className="h-3 w-3" />
                                </Button>
                            </div>
                        </div>
                    </div>

                    {/* Markdown Export */}
                    <div className="p-3 rounded-lg border border-border hover:border-primary/30 transition-colors">
                        <div className="flex items-center justify-between">
                            <div className="flex items-center gap-2">
                                <FileText className="h-4 w-4 text-green-400" />
                                <div>
                                    <p className="text-sm font-medium">Markdown Plan</p>
                                    <p className="text-[10px] text-muted-foreground">
                                        Readable architecture + implementation order
                                    </p>
                                </div>
                            </div>
                            <div className="flex gap-1">
                                <Button
                                    variant="ghost"
                                    size="sm"
                                    className="h-7 text-xs"
                                    onClick={() => handleCopy(generateMarkdown(), "md")}
                                >
                                    {copied === "md" ? (
                                        <Check className="h-3 w-3" />
                                    ) : (
                                        <Copy className="h-3 w-3" />
                                    )}
                                </Button>
                                <Button
                                    variant="ghost"
                                    size="sm"
                                    className="h-7 text-xs"
                                    onClick={() =>
                                        handleDownload(
                                            generateMarkdown(),
                                            `${projectName}-plan.md`,
                                            "text/markdown"
                                        )
                                    }
                                >
                                    <Download className="h-3 w-3" />
                                </Button>
                            </div>
                        </div>
                    </div>

                    <Separator />

                    {/* AI Prompt Pack */}
                    <Button
                        variant="outline"
                        className="w-full gap-2 text-xs"
                        onClick={handleGeneratePromptPack}
                        disabled={isGeneratingPrompts}
                    >
                        {isGeneratingPrompts ? (
                            <Loader2 className="h-3.5 w-3.5 animate-spin" />
                        ) : (
                            <Sparkles className="h-3.5 w-3.5" />
                        )}
                        Generate AI Prompt Pack
                    </Button>
                    <p className="text-[10px] text-muted-foreground text-center">
                        AI-generated implementation prompts for Cursor/Claude/Lovable
                    </p>

                    <div className="flex items-center justify-center gap-2">
                        <Badge variant="secondary" className="text-[10px]">
                            {nodes.length} components
                        </Badge>
                        <Badge variant="secondary" className="text-[10px]">
                            {edges.length} connections
                        </Badge>
                    </div>
                </div>
            </DialogContent>
        </Dialog>
    );
}

